import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
    variable: "--font-roboto",
});

export const metadata = {
    title: "Beelancer Services",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="pt-BR">
            <body className={`${roboto.variable} antialiased`}>
                {children}
            </body>
        </html>
    );
}
